version: '3.8'

services:
  # Servicio de MongoDB
  mongodb:
    image: mongo:6.0
    container_name: crud_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: db_microservicios
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - crud_network

  # Servicio de la aplicación Node.js
  app:
    build: .
    container_name: crud_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:admin@mongodb:27017/db_microservicios?authSource=admin
    networks:
      - crud_network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:

# Redes
networks:
  crud_network:
    driver: bridge