version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: name-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql       # <── aquí se guardan los datos
    networks:
      - mynet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    networks:
      - mynet

networks:
  mynet:

volumes:
  mysql_data:   # volumen nombrado para persistencia
